# Generated by Django 5.2.13 on 2026-04-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='blur_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_avif',
            field=models.ImageField(blank=True, null=True, upload_to='previews/avif/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_webp',
            field=models.ImageField(blank=True, null=True, upload_to='previews/webp/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
