# Generated by Django 5.2.13 on 2026-04-23 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_orientation_photo_orientation_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='orientation',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='orientation_link',
            new_name='orientation',
        ),
        migrations.AlterField(
            model_name='photo',
            name='orientation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='catalog.orientation'),
        ),
    ]
